-- 코드를 입력하세요
SELECT
ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
from
ANIMAL_INS
    inner join
    ANIMAL_OUTS
    on
    ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
where
ANIMAL_INS.SEX_UPON_INTAKE LIKE "Intact%"
and
NOT ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Intact%"
order by
ANIMAL_INS.ANIMAL_ID;