-- 코드를 입력하세요
SELECT
ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
from
ANIMAL_INS
    inner join
    ANIMAL_OUTS
    on
    ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
order by
DATEDIFF(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME) desc
limit
2;