-- 코드를 입력하세요
with ONLY_TRUCK as (
    SELECT
    CAR_ID, DAILY_FEE
    from
    CAR_RENTAL_COMPANY_CAR C
    where
    CAR_TYPE = "트럭"
),
FEE_TRUCK as (
    select
    DURATION_TYPE, DISCOUNT_RATE
    from
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    where
    CAR_TYPE = "트럭"
)

select
HISTORY_ID,
CASE
    WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 7 and DATEDIFF(END_DATE, START_DATE)+1 < 30)
    THEN ROUND((DAILY_FEE -(DAILY_FEE * ((SELECT DISCOUNT_RATE FROM FEE_TRUCK WHERE DURATION_TYPE = '7일 이상') * 0.01))) * (DATEDIFF(END_DATE, START_DATE)+1))
    WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 30 and DATEDIFF(END_DATE, START_DATE)+1 < 90)
    THEN ROUND((DAILY_FEE -(DAILY_FEE * ((SELECT DISCOUNT_RATE FROM FEE_TRUCK WHERE DURATION_TYPE = '30일 이상') * 0.01))) * (DATEDIFF(END_DATE, START_DATE)+1))
    WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 90)
    THEN ROUND((DAILY_FEE -(DAILY_FEE * ((SELECT DISCOUNT_RATE FROM FEE_TRUCK WHERE DURATION_TYPE = '90일 이상') * 0.01))) * (DATEDIFF(END_DATE, START_DATE)+1))
    ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1)
END as FEE
from
CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    join
    ONLY_TRUCK
    on
    H.CAR_ID = ONLY_TRUCK.CAR_ID
order by
FEE desc, HISTORY_ID desc
;