-- 코드를 입력하세요

# SELECT CREATED_DATE
# from USED_GOODS_BOARD
# where CREATED_DATE
# between "2022-10-01" and "2022-10-31";

# select CREATED_DATE
# from USED_GOODS_REPLY
# where CREATED_DATE
# between "2022-10-01" and "2022-10-31";

select 
USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID, 
USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, 
USED_GOODS_REPLY.CONTENTS, date_format(USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD
inner join USED_GOODS_REPLY on USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
where USED_GOODS_BOARD.CREATED_DATE
between "2022-10-01" and "2022-10-31"
order by USED_GOODS_REPLY.CREATED_DATE ASC, USED_GOODS_BOARD.TITLE ASC;
